FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher@sha256:8f15ebccb4fb3bc723db10bddddd13c43d464c71a4edddec578ab2477822a1c5
MAINTAINER ZHo
