FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-uploader@sha256:2ac1b03e3a262511d6bfdc7c2d05db517dc1c785830f383f132b8d97dba22947
MAINTAINER ZHo
